### ISSUE TITLE
function name changes due to PEFT package update

### ISSUE THREAD

**Issue by solangii** [henryqin1997/alpaca-lora#1]
When I run `finetune.py` and `finetune_infobatch.py`, I get this error:
```
ImportError: cannot import name 'prepare_model_for_int8_training' from 'peft' (/home/work/.local/lib/python3.10/site-packages/peft/__init__.py)
```
According to this issue([link](https://github.com/huggingface/peft/issues/1583#issuecomment-2017550784
)),  `prepare_model_for_int8_training` function has been removed. So I think it use `prepare_model_for_kbit_training` instead.

These functions seem to appear here:
https://github.com/henryqin1997/alpaca-lora/blob/387335bfd32892c72f6ef13c44e8596f684a5a8a/finetune.py#L20
https://github.com/henryqin1997/alpaca-lora/blob/387335bfd32892c72f6ef13c44e8596f684a5a8a/finetune.py#L174
https://github.com/henryqin1997/alpaca-lora/blob/387335bfd32892c72f6ef13c44e8596f684a5a8a/finetune_infobatch.py#L22
https://github.com/henryqin1997/alpaca-lora/blob/387335bfd32892c72f6ef13c44e8596f684a5a8a/finetune_infobatch.py#L176

If you just change their names, it should work fine :)

**Comment by henryqin1997** [comment]
Thank you for raising this issue! Without a docker sometimes the dependencies would change. I made an update.
